#\DeclareLyXModule{pLyX}
#DescriptionBegin
# Provides custom insets for specifying python scripts
# to run. To be used with the converter pLyX.py which
# exports from LyX to pLyX format. 
#DescriptionEnd
#
#v.1.0 2013-01-01
#Author: Andrew Parsloe <aparsloe@clear.net.nz>
#
Preamble
	\newcommand{\pLyXgobble}[1]{}
EndPreamble

# All inset names begin with a full stop
# to aid alphabetical grouping
######## MultiPar	1	########

#(upper-case initial letter for this inset only)
InsetLayout "Flex:.Run script(s)"
  LyXType			custom
  LatexType     	command
  LatexName     	pLyXgobble
  Decoration		classic
  ContentAsLabel	0
  Font
	Misc			no_emph
	Misc			no_bar
	Misc			no_noun
	Misc			no_strikeout
	Misc			no_uuline
	Misc			no_uwave
	Family			roman
	Series			medium
	Shape			up
	Size			normal
	Color			none
  EndFont
  LabelFont
	Color			blue
  EndFont
  LabelString		"Run script(s)"
  MultiPar			1
  ResetsFont		0
  Spellcheck		0
End

InsetLayout Flex:.[argument]
  CopyStyle			"Flex:.Run script(s)"
  ContentAsLabel	1
  LabelFont
	Color			none
  EndFont
  LabelString		.
  FreeSpacing		0
End

InsetLayout "Flex:.expand macro|txtmacs"
  CopyStyle			"Flex:.Run script(s)"
  ContentAsLabel	1
  LabelString		Macro
  FreeSpacing		0
End

######## MultiPar	0	########

InsetLayout Flex:.stop|break
  CopyStyle			"Flex:.Run script(s)"
  LabelString		Stop
  MultiPar			0
End

InsetLayout "Flex:.calculate formula|calcul8"
  CopyStyle			"Flex:.Run script(s)"
  ContentAsLabel	1
  LabelString		Calculate
  MultiPar			0
End

InsetLayout "Flex:.sort table|sortable"
  CopyStyle			"Flex:.Run script(s)"
  ContentAsLabel	1
  LabelString		"Sort table"
  MultiPar			0
End

InsetLayout "Flex:.sort list|sortlist"
  CopyStyle			"Flex:.Run script(s)"
  ContentAsLabel	1
  LabelString		"Sort list"
  MultiPar			0
End


